### PR TITLE
chore: move bibxml_string serialization to bibxml-service

### PR DESCRIPTION
**Pull request by stefanomunarini**

### CODE REVIEW

**Comment by stefanomunarini** [comment]
Serializer is moved out of this repository into https://github.com/stefanomunarini/bibxml-service/commit/1a4f7b9d4ecd0c4d7e63cd0cbeaa86786d06d8b0 .

**Comment by stefanomunarini** [comment]
#43

**Comment by strogonoff** [comment]
Test errors due to data validation are unrelated and will be discussed separately.

**Comment by strogonoff** [comment]
@stefanomunarini it would help if you add a description of the change to Changelog within the same PR, this way we don’t need to remember to do it during release (it’s easy to forget).

**Review by strogonoff — COMMENTED** [review]
It’s OK but documentation (in Changelog and possibly other sections, manual inspection and grep can be used to determine) wasn’t updated.

**Pull request merged**
